const TAROT_CARDS = [
  // ARCANOS MAIORES
  { id: 0, name: "O Louco", arcana: "major", number: "0", suit: null,
    keywords: ["liberdade","inocência","aventura","começos"],
    upright: "Novos começos, inocência, espírito livre, aventura, espontaneidade. O Louco representa um salto de fé, a disposição de embarcar em uma jornada desconhecida com confiança total no universo. Energia jovial, desapego e abertura ao que está por vir.",
    reversed: "Imprudência, risco desnecessário, imaturidade, irresponsabilidade. Pode indicar que você está tomando decisões sem pensar nas consequências ou se recusando a crescer e assumir responsabilidades.",
    element: "Ar", planet: "Urano", symbol: "☿" },
  { id: 1, name: "O Mago", arcana: "major", number: "I", suit: null,
    keywords: ["vontade","poder","habilidade","manifestação"],
    upright: "Poder de manifestação, habilidade, vontade, recursos disponíveis. O Mago tem todas as ferramentas necessárias — os quatro elementos à sua disposição. Momento de agir com intenção clara e canalizar sua energia para criar resultados concretos.",
    reversed: "Manipulação, ilusão, talentos desperdiçados, enganação. Cuidado com promessas vazias ou com alguém que usa suas habilidades de forma enganosa. Pode indicar bloqueio criativo ou falta de direção.",
    element: "Ar", planet: "Mercúrio", symbol: "☿" },
  { id: 2, name: "A Sacerdotisa", arcana: "major", number: "II", suit: null,
    keywords: ["intuição","mistério","sabedoria interior","subconsciência"],
    upright: "Intuição, sabedoria oculta, subconsciente, paciência. A Alta Sacerdotisa guarda os mistérios do universo. Convite para confiar na intuição, mergulhar no interior e aguardar o momento certo. O que não está visível agora será revelado.",
    reversed: "Segredos revelados, superficialidade, falta de intuição, informação retida. Pode indicar que você está ignorando sua voz interior ou que verdades ocultas estão prestes a emergir.",
    element: "Água", planet: "Lua", symbol: "☽" },
  { id: 3, name: "A Imperatriz", arcana: "major", number: "III", suit: null,
    keywords: ["fertilidade","abundância","natureza","criatividade"],
    upright: "Fertilidade, abundância, criatividade, nutrição, natureza. A Imperatriz representa a força feminina criativa, a maternidade e a conexão com a terra. Período de crescimento, abundância material e emocional, criatividade florescendo.",
    reversed: "Bloqueio criativo, dependência excessiva, sufocamento, falta de crescimento. Pode indicar negligência de si mesmo ou de outros, ou uma relação sufocante que impede o crescimento natural.",
    element: "Terra", planet: "Vênus", symbol: "♀" },
  { id: 4, name: "O Imperador", arcana: "major", number: "IV", suit: null,
    keywords: ["autoridade","estrutura","estabilidade","paternidade"],
    upright: "Autoridade, estrutura, estabilidade, proteção, liderança. O Imperador representa o princípio masculino, a ordem e a lei. Momento de estabelecer estruturas sólidas, assumir responsabilidades e exercer liderança com sabedoria e firmeza.",
    reversed: "Tirania, rigidez excessiva, falta de disciplina, controle abusivo. Pode indicar autoritarismo, incapacidade de flexibilizar regras ou uma figura paterna problemática na vida.",
    element: "Fogo", planet: "Marte", symbol: "♂" },
  { id: 5, name: "O Hierofante", arcana: "major", number: "V", suit: null,
    keywords: ["tradição","espiritualidade","conformidade","ensino"],
    upright: "Tradição, espiritualidade, ensinamentos, conformidade, instituições. O Hierofante guarda o conhecimento sagrado e as tradições. Busca por orientação espiritual, respeito às convenções e aprendizado com mestres e tradições estabelecidas.",
    reversed: "Desafio às convenções, rebeldia, novas abordagens, dogmatismo. Pode indicar necessidade de questionar dogmas estabelecidos ou libertação de estruturas que não servem mais ao seu crescimento.",
    element: "Terra", planet: "Touro", symbol: "♉" },
  { id: 6, name: "Os Enamorados", arcana: "major", number: "VI", suit: null,
    keywords: ["amor","escolha","harmonia","relacionamentos"],
    upright: "Amor, harmonia, relacionamentos, escolhas, valores alinhados. Os Enamorados representam não apenas o amor romântico, mas todas as escolhas feitas pelo coração. Alinhamento de valores, união profunda e decisões baseadas no amor.",
    reversed: "Desarmonia, desequilíbrio, má decisão, ruptura. Pode indicar conflito de valores, relacionamento desequilibrado ou uma escolha importante sendo evitada.",
    element: "Ar", planet: "Gêmeos", symbol: "♊" },
  { id: 7, name: "O Carro", arcana: "major", number: "VII", suit: null,
    keywords: ["vitória","determinação","controle","movimento"],
    upright: "Vitória, determinação, controle, sucesso através da força de vontade. O Carro representa a capacidade de avançar com determinação, controlando forças opostas. Superação de obstáculos, triunfo e movimento decidido em direção aos objetivos.",
    reversed: "Falta de controle, agressividade, derrota, obstáculos. Pode indicar que você está sendo conduzido pelas circunstâncias em vez de guiá-las, ou que a força bruta está sendo usada onde seria necessária sutileza.",
    element: "Água", planet: "Câncer", symbol: "♋" },
  { id: 8, name: "A Força", arcana: "major", number: "VIII", suit: null,
    keywords: ["coragem","paciência","compaixão","força interior"],
    upright: "Força interior, coragem, paciência, compaixão, autocontrole. A Força não é a força bruta, mas a capacidade de dominar impulsos primitivos com amor e gentileza. Momento de enfrentar desafios com calma, paciência e confiança interior.",
    reversed: "Fraqueza, insegurança, falta de autoconfiança, covardia. Pode indicar que você está duvidando de suas próprias capacidades ou deixando medos primitivos guiarem suas ações.",
    element: "Fogo", planet: "Leão", symbol: "♌" },
  { id: 9, name: "O Eremita", arcana: "major", number: "IX", suit: null,
    keywords: ["solitude","introspecção","sabedoria","busca interior"],
    upright: "Solitude, introspecção, sabedoria interior, busca espiritual, orientação. O Eremita retira-se do mundo para encontrar a luz interior. Momento de reflexão profunda, busca por respostas internas e conexão com a sabedoria que vem do silêncio.",
    reversed: "Isolamento excessivo, solidão indesejada, reclusão, rejeição da orientação. Pode indicar que o isolamento está se tornando prejudicial ou que há resistência em buscar ou aceitar ajuda.",
    element: "Terra", planet: "Virgem", symbol: "♍" },
  { id: 10, name: "A Roda da Fortuna", arcana: "major", number: "X", suit: null,
    keywords: ["destino","ciclos","mudança","sorte"],
    upright: "Destino, ciclos da vida, boa sorte, ponto de virada. A Roda da Fortuna gira constantemente — momentos de alta e baixa fazem parte do ciclo da vida. Aceitação das mudanças inevitáveis e confiança de que tudo gira a seu favor.",
    reversed: "Má sorte, resistência à mudança, ciclos negativos, falta de controle. Pode indicar que você está lutando contra forças maiores ou que está preso em padrões que precisam ser quebrados.",
    element: "Fogo", planet: "Júpiter", symbol: "♃" },
  { id: 11, name: "A Justiça", arcana: "major", number: "XI", suit: null,
    keywords: ["justiça","verdade","equilíbrio","causa e efeito"],
    upright: "Justiça, verdade, equilíbrio, lei, causa e efeito. A Justiça representa a lei cármica e a responsabilidade por nossas ações. Momento de tomar decisões baseadas em fatos, aceitar as consequências de escolhas passadas e buscar o equilíbrio.",
    reversed: "Injustiça, desonestidade, falta de responsabilidade, julgamento desequilibrado. Pode indicar que a justiça está sendo negada ou que você está evitando responsabilidades pelas suas ações.",
    element: "Ar", planet: "Libra", symbol: "♎" },
  { id: 12, name: "O Enforcado", arcana: "major", number: "XII", suit: null,
    keywords: ["suspensão","sacrifício","nova perspectiva","pausa"],
    upright: "Suspensão, sacrifício, nova perspectiva, entrega, pausa necessária. O Enforcado escolheu ser suspenso para ver o mundo de outro ângulo. Momento de pause, rendição ao que não pode ser controlado e abertura para novas perspectivas.",
    reversed: "Atraso, resistência, martirio desnecessário, estagnação. Pode indicar que o sacrifício está sendo feito em vão ou que há resistência em deixar ir o que precisa ser liberado.",
    element: "Água", planet: "Netuno", symbol: "♆" },
  { id: 13, name: "A Morte", arcana: "major", number: "XIII", suit: null,
    keywords: ["transformação","encerramento","transição","renovação"],
    upright: "Transformação, encerramento, transição, renovação, mudança inevitável. A Morte raramente indica morte literal — representa o fim de um ciclo e o início de outro. Liberação do passado, transformação profunda e renascimento para algo novo.",
    reversed: "Resistência à mudança, estagnação, medo da transformação, fim retardado. Pode indicar apego excessivo ao passado ou incapacidade de deixar ir o que já não serve.",
    element: "Água", planet: "Escorpião", symbol: "♏" },
  { id: 14, name: "A Temperança", arcana: "major", number: "XIV", suit: null,
    keywords: ["equilíbrio","moderação","paciência","propósito"],
    upright: "Equilíbrio, moderação, paciência, propósito, alquimia. A Temperança mistura com maestria elementos aparentemente opostos. Momento de encontrar o meio-termo, ser paciente e trabalhar em harmonia para alcançar resultados duradouros.",
    reversed: "Desequilíbrio, excesso, falta de moderação, conflito interno. Pode indicar que você está indo a extremos ou que há falta de harmonia entre aspectos importantes da vida.",
    element: "Fogo", planet: "Sagitário", symbol: "♐" },
  { id: 15, name: "O Diabo", arcana: "major", number: "XV", suit: null,
    keywords: ["aprisionamento","vícios","materialismo","sombra"],
    upright: "Aprisionamento, vícios, materialismo, ilusão, sombra. O Diabo representa os padrões que nos aprisionam — mas as correntes são soltas. Reconhecimento de vícios, dependências e padrões de pensamento negativos que limitam a liberdade.",
    reversed: "Libertação, reconhecimento de padrões negativos, independência, rompimento de vícios. Momento de libertar-se das correntes que você mesmo criou e escolher um caminho mais saudável.",
    element: "Terra", planet: "Capricórnio", symbol: "♑" },
  { id: 16, name: "A Torre", arcana: "major", number: "XVI", suit: null,
    keywords: ["ruptura","revelação","caos","transformação súbita"],
    upright: "Ruptura, revelação súbita, caos, transformação, destruição do falso. A Torre cai quando as fundações são falsas. Mudanças drásticas e inesperadas que, apesar do caos inicial, liberam espaço para algo mais verdadeiro e sólido ser construído.",
    reversed: "Resistência à transformação necessária, catástrofe evitada, libertação interna. Pode indicar que você está adiando uma mudança inevitável ou que uma crise interna está sendo processada.",
    element: "Fogo", planet: "Marte", symbol: "♂" },
  { id: 17, name: "A Estrela", arcana: "major", number: "XVII", suit: null,
    keywords: ["esperança","inspiração","renovação","fé"],
    upright: "Esperança, inspiração, renovação espiritual, serenidade, fé. Após a tempestade, a Estrela brilha. Momento de renovação, cura profunda e reconexão com o propósito de vida. A luz guia mesmo nas noites mais escuras.",
    reversed: "Desesperança, falta de fé, desconexão espiritual, pessimismo. Pode indicar que a fé está abalada ou que há dificuldade em ver a luz no fim do túnel.",
    element: "Ar", planet: "Aquário", symbol: "♒" },
  { id: 18, name: "A Lua", arcana: "major", number: "XVIII", suit: null,
    keywords: ["ilusão","subconsciente","medo","intuição profunda"],
    upright: "Ilusão, subconsciênte, medo, confusão, intuição profunda. A Lua ilumina o que está oculto nas sombras. Momento de prestar atenção aos sonhos, medos e intuições mais profundas. Nem tudo é o que parece ser.",
    reversed: "Confusão dissipando, medo liberado, clareza chegando, enganos revelados. Pode indicar que as ilusões estão se dissipando ou que medos profundos estão sendo reconhecidos e processados.",
    element: "Água", planet: "Peixes", symbol: "♓" },
  { id: 19, name: "O Sol", arcana: "major", number: "XIX", suit: null,
    keywords: ["sucesso","vitalidade","alegria","clareza"],
    upright: "Sucesso, vitalidade, alegria, clareza, otimismo, triunfo. O Sol brilha sem ambiguidade — traz luz, calor e vida. Período de grande otimismo, sucesso nos empreendimentos, saúde e alegria genuína.",
    reversed: "Pessimismo, falta de entusiasmo, sucesso temporário, energia baixa. Pode indicar que o brilho interno está temporariamente obscurecido ou que há excessiva modéstia impedindo reconhecer os próprios sucessos.",
    element: "Fogo", planet: "Sol", symbol: "☀" },
  { id: 20, name: "O Julgamento", arcana: "major", number: "XX", suit: null,
    keywords: ["julgamento","absolvição","renovação","chamado"],
    upright: "Julgamento, absolvição, renovação, chamado interior, despertar. O Julgamento convoca para uma avaliação honesta do passado e um renascimento. Momento de atender ao chamado interior, fazer as pazes com o passado e abraçar uma nova versão de si mesmo.",
    reversed: "Autocrítica excessiva, ignorar o chamado, arrependimento, julgamento injusto. Pode indicar que você está sendo muito duro consigo mesmo ou ignorando um chamado importante de transformação.",
    element: "Fogo", planet: "Plutão", symbol: "♇" },
  { id: 21, name: "O Mundo", arcana: "major", number: "XXI", suit: null,
    keywords: ["conclusão","integração","realização","totalidade"],
    upright: "Conclusão, integração, realização, totalidade, sucesso completo. O Mundo representa a conclusão bem-sucedida de um ciclo importante. Sensação de completude, realização de objetivos e integração de todas as experiências vividas.",
    reversed: "Ciclo incompleto, atraso, falta de conclusão, busca da perfeição. Pode indicar que algo importante ainda não foi finalizado ou que há resistência em aceitar a completude do caminho percorrido.",
    element: "Terra", planet: "Saturno", symbol: "♄" },

  // COPAS (1-14)
  { id: 22, name: "Ás de Copas", arcana: "minor", number: "1", suit: "cups",
    keywords: ["novo amor","emoções","intuição","início emocional"],
    upright: "Novo começo emocional, amor abundante, intuição, conexão espiritual. O Ás de Copas transborda com possibilidades emocionais. Abertura do coração para o amor, criatividade emocional e conexão profunda com o divino.",
    reversed: "Amor bloqueado, emoções reprimidas, vazio emocional. Dificuldade em abrir o coração ou conectar-se com os próprios sentimentos.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 23, name: "Dois de Copas", arcana: "minor", number: "2", suit: "cups",
    keywords: ["união","parceria","amor mútuo","conexão"],
    upright: "União, parceria romântica, amor mútuo, conexão profunda, compromisso. Dois corações que se encontram em harmonia. Relacionamento equilibrado baseado em respeito mútuo e afeto genuíno.",
    reversed: "Desequilíbrio no relacionamento, separação, ruptura, incompatibilidade. Pode indicar conflito ou desencontro entre duas pessoas.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 24, name: "Três de Copas", arcana: "minor", number: "3", suit: "cups",
    keywords: ["celebração","amizade","comunidade","alegria"],
    upright: "Celebração, amizade, comunidade, alegria compartilhada, abundância. Momento de festejo com pessoas queridas, conquistas celebradas em grupo e apoio mútuo.",
    reversed: "Excessos, isolamento, triângulo amoroso, fofoca. Cuidado com excesso de festas ou conflitos dentro do grupo.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 25, name: "Quatro de Copas", arcana: "minor", number: "4", suit: "cups",
    keywords: ["contemplação","apatia","reavaliação","descontentamento"],
    upright: "Contemplação, apatia, reavaliação, introspecção, tédio emocional. Período de questionamento interior sobre o que realmente importa. Uma oportunidade pode estar sendo ignorada.",
    reversed: "Renovação de interesse, motivação, aproveitando oportunidades. Saída da letargia e abertura para novas experiências.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 26, name: "Cinco de Copas", arcana: "minor", number: "5", suit: "cups",
    keywords: ["luto","perda","arrependimento","tristeza"],
    upright: "Luto, perda, arrependimento, foco no negativo. Momento de tristeza por algo perdido, mas há ainda copos em pé — o que permanece tem valor.",
    reversed: "Aceitação, seguir em frente, perdão, recuperação. Capacidade de encontrar paz após a perda.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 27, name: "Seis de Copas", arcana: "minor", number: "6", suit: "cups",
    keywords: ["nostalgia","infância","inocência","passado"],
    upright: "Nostalgia, memórias da infância, inocência, presentes do passado. Reconexão com alegrias simples e lembranças que nutrem a alma.",
    reversed: "Preso no passado, ingenuidade, idealização do passado. Dificuldade em avançar por apego a memórias.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 28, name: "Sete de Copas", arcana: "minor", number: "7", suit: "cups",
    keywords: ["ilusão","fantasias","escolhas","desejos"],
    upright: "Ilusões, fantasias, muitas escolhas, sonhos, imaginação. Período de muitas possibilidades — mas cuidado para não se perder em devaneios.",
    reversed: "Clareza, decisão, livre de ilusões, alinhamento. Capacidade de ver as coisas como realmente são e fazer escolhas conscientes.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 29, name: "Oito de Copas", arcana: "minor", number: "8", suit: "cups",
    keywords: ["abandono","busca","partir","decepção"],
    upright: "Abandono do que não serve, busca por significado, partir em jornada espiritual. Coragem de deixar para trás o que não mais satisfaz.",
    reversed: "Medo de partir, retorno, estagnação, apego. Dificuldade em deixar ir situações que já não nutrem.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 30, name: "Nove de Copas", arcana: "minor", number: "9", suit: "cups",
    keywords: ["satisfação","realização","desejo","gratidão"],
    upright: "Satisfação, realização de desejos, gratidão, contentamento. A carta dos desejos realizados — momento de grande satisfação emocional e material.",
    reversed: "Insatisfação, materialismo, desejo excessivo, sonhos não realizados. Apesar das conquistas externas, falta algo internamente.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 31, name: "Dez de Copas", arcana: "minor", number: "10", suit: "cups",
    keywords: ["felicidade","família","harmonia","realização"],
    upright: "Felicidade familiar, harmonia, realização emocional completa, lar. O arco-íris após a chuva — alegria duradoura e relacionamentos harmoniosos.",
    reversed: "Dissonância familiar, valores desalinhados, harmonia perturbada. Tensões no lar ou dificuldades em criar a família harmoniosa desejada.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 32, name: "Pajem de Copas", arcana: "minor", number: "11", suit: "cups",
    keywords: ["curiosidade","mensagem emocional","sonhos","sensibilidade"],
    upright: "Mensageiro emocional, curiosidade, criatividade, sensibilidade. Traz notícias emocionais, um convite para explorar os sentimentos com abertura.",
    reversed: "Imaturidade emocional, manipulação, frivolidade. Pode indicar irresponsabilidade emocional ou um jovem problemático.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 33, name: "Cavaleiro de Copas", arcana: "minor", number: "12", suit: "cups",
    keywords: ["romance","charme","idealismo","proposta"],
    upright: "Romance, charme, idealismo, proposta, chamado do coração. O cavaleiro segue o coração sem hesitar. Convites românticos e propostas que vêm com sinceridade.",
    reversed: "Capricho, ciúme, moodiness, decepções. Romantismo excessivo que pode levar a decepções ou comportamento caprichoso.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 34, name: "Rainha de Copas", arcana: "minor", number: "13", suit: "cups",
    keywords: ["compaixão","intuição","cura","empatia"],
    upright: "Compaixão, intuição, cura, empatia profunda, nutrição emocional. A rainha cuida com sabedoria emocional, intuitiva e amorosa.",
    reversed: "Dependência emocional, insegurança, manipulação emocional. Tendência a absorver emoções dos outros de forma não saudável.",
    element: "Água", planet: null, symbol: "🏆" },
  { id: 35, name: "Rei de Copas", arcana: "minor", number: "14", suit: "cups",
    keywords: ["maturidade emocional","diplomacia","sabedoria","equilíbrio"],
    upright: "Maturidade emocional, diplomacia, sabedoria, equilíbrio entre emoção e razão. Líder que governa com o coração e a mente em harmonia.",
    reversed: "Manipulação emocional, instabilidade, frieza. Pode indicar repressão emocional ou uso das emoções para manipular outros.",
    element: "Água", planet: null, symbol: "🏆" },

  // ESPADAS (1-14)
  { id: 36, name: "Ás de Espadas", arcana: "minor", number: "1", suit: "swords",
    keywords: ["clareza","verdade","pensamento","novos começos mentais"],
    upright: "Clareza mental, verdade, novos começos intelectuais, corte através da confusão. A espada da mente corta o véu das ilusões. Momento de grande clareza e comunicação direta.",
    reversed: "Confusão, injustiça, verdade cruel, caos mental. Falta de clareza ou uso da verdade de forma destrutiva.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 37, name: "Dois de Espadas", arcana: "minor", number: "2", suit: "swords",
    keywords: ["bloqueio","impasse","decisão difícil","negação"],
    upright: "Impasse, decisão difícil, bloqueio mental, equilíbrio precário. A pessoa de olhos vendados recusa-se a ver a verdade. Necessidade de enfrentar a situação e tomar uma decisão.",
    reversed: "Confusão, sobrecarga de informação, decisão inevitável. As vendas estão caindo — é hora de ver e decidir.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 38, name: "Três de Espadas", arcana: "minor", number: "3", suit: "swords",
    keywords: ["tristeza","dor de coração","traição","sofrimento"],
    upright: "Tristeza, dor de coração, traição, sofrimento, separação. A dor é real e precisa ser sentida para ser curada. Reconhecimento honesto do sofrimento.",
    reversed: "Recuperação, perdão, cura de dores antigas. O processo de cura está em andamento após grande sofrimento.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 39, name: "Quatro de Espadas", arcana: "minor", number: "4", suit: "swords",
    keywords: ["descanso","recuperação","contemplação","retiro"],
    upright: "Descanso, recuperação, contemplação, retiro. Após batalhas intensas, o guerreiro precisa descansar. Pausa necessária para restaurar as forças.",
    reversed: "Exaustão, burnout, retorno à ação antes do tempo, inquietação. Dificuldade em descansar ou necessidade urgente de retornar à ação.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 40, name: "Cinco de Espadas", arcana: "minor", number: "5", suit: "swords",
    keywords: ["conflito","derrota","traição","vitória vazia"],
    upright: "Conflito, derrota, vitória vazia, desonra, traição. Vitória conquistada com táticas desonestas ou às custas de relacionamentos importantes.",
    reversed: "Reconciliação, arrependimento, passando pelo conflito. Capacidade de superar conflitos passados e buscar a paz.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 41, name: "Seis de Espadas", arcana: "minor", number: "6", suit: "swords",
    keywords: ["transição","movimento","cura","saindo da turbulência"],
    upright: "Transição, movimento para águas mais calmas, cura gradual, passagem. Saindo de um período difícil em direção a maior tranquilidade.",
    reversed: "Resistência à mudança, bagagem emocional, retorno de problemas. Dificuldade em deixar o passado para trás.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 42, name: "Sete de Espadas", arcana: "minor", number: "7", suit: "swords",
    keywords: ["engano","estratégia","furtividade","evasão"],
    upright: "Engano, estratégia, furtividade, evasão, independência. Às vezes é necessário ser estratégico e sutil para alcançar objetivos.",
    reversed: "Confissão, arrependimento, impostor revelado, verdade à tona. Segredos sendo revelados ou necessidade de encarar a verdade.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 43, name: "Oito de Espadas", arcana: "minor", number: "8", suit: "swords",
    keywords: ["aprisionamento","restrição","pensamentos limitantes","vitimismo"],
    upright: "Aprisionamento mental, restrição, pensamentos limitantes, vitimismo. As restrições são em grande parte criadas pela mente — a liberdade está mais próxima do que parece.",
    reversed: "Libertação, autolibertação, novo ponto de vista, empoderamento. Reconhecimento de que as amarras eram mentais e capacidade de se libertar.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 44, name: "Nove de Espadas", arcana: "minor", number: "9", suit: "swords",
    keywords: ["ansiedade","pesadelos","preocupação","angústia"],
    upright: "Ansiedade, pesadelos, preocupação excessiva, angústia noturna. Os piores medos da mente acordada às 3 da manhã. Muitas vezes a situação não é tão terrível quanto parece.",
    reversed: "Esperança, saída da dificuldade, alívio, fim da preocupação. O alvorecer após a noite mais escura está chegando.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 45, name: "Dez de Espadas", arcana: "minor", number: "10", suit: "swords",
    keywords: ["fim doloroso","traição","colapso","novo amanhecer"],
    upright: "Fim doloroso, traição, colapso, mas também novo amanhecer. O pior já passou — a única direção agora é para cima.",
    reversed: "Resistência ao inevitável, recuperação, sobrevivência. A dificuldade está sendo superada ou há resistência em aceitar um fim necessário.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 46, name: "Pajem de Espadas", arcana: "minor", number: "11", suit: "swords",
    keywords: ["curiosidade","vigilância","pensamento rápido","novidade"],
    upright: "Mente curiosa, vigilância, pensamento rápido, mensagens, novidades. Jovem espírito intelectual pronto para aprender e comunicar.",
    reversed: "Fofoca, insensibilidade, falta de planejamento, impulsividade verbal. Palavras sem filtro que causam danos.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 47, name: "Cavaleiro de Espadas", arcana: "minor", number: "12", suit: "swords",
    keywords: ["ação","ambição","coragem","impulsividade"],
    upright: "Ação rápida, ambição, coragem, determinação, inteligência em movimento. Parte em grande velocidade em direção aos objetivos, às vezes sem pensar nas consequências.",
    reversed: "Impulsividade destrutiva, agressão verbal, impaciência. Ação antes da reflexão causando danos colaterais.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 48, name: "Rainha de Espadas", arcana: "minor", number: "13", suit: "swords",
    keywords: ["independência","julgamento","clareza","comunicação direta"],
    upright: "Independência, julgamento claro, comunicação direta, sabedoria através da experiência. Mente afiada que combina intelecto com experiência de vida.",
    reversed: "Frieza, crueldade, ressentimento, isolamento. Inteligência usada de forma fria e distante.",
    element: "Ar", planet: null, symbol: "⚔" },
  { id: 49, name: "Rei de Espadas", arcana: "minor", number: "14", suit: "swords",
    keywords: ["autoridade intelectual","lógica","clareza","decisão"],
    upright: "Autoridade intelectual, lógica, clareza mental, decisão firme, verdade. Governa com a mente — justo, direto e analítico.",
    reversed: "Manipulação, tirania mental, crueldade, desonestidade. Inteligência usada para controlar ou manipular.",
    element: "Ar", planet: null, symbol: "⚔" },

  // PAUS (1-14)
  { id: 50, name: "Ás de Paus", arcana: "minor", number: "1", suit: "wands",
    keywords: ["inspiração","potencial","novos começos","criatividade"],
    upright: "Inspiração, potencial criativo, novos começos, energia vital. A centelha que acende a chama. Potencial bruto esperando ser direcionado para algo grande.",
    reversed: "Atrasos, falta de motivação, energia bloqueada. A faísca está lá mas ainda não encontrou o momento certo para acender.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 51, name: "Dois de Paus", arcana: "minor", number: "2", suit: "wands",
    keywords: ["planejamento","progresso","decisões","expansão"],
    upright: "Planejamento, progresso, decisões futuras, expansão, visão de longo prazo. Em pé sobre a torre, olhando para o horizonte — o mundo está aos seus pés.",
    reversed: "Medo do desconhecido, falta de planejamento, planos que desmoronam. Hesitação diante das possibilidades.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 52, name: "Três de Paus", arcana: "minor", number: "3", suit: "wands",
    keywords: ["expansão","visão","empreendimento","progresso"],
    upright: "Expansão, visão de longo alcance, empreendimento, aguardando resultados. Os navios estão no mar — os planos foram lançados e agora é hora de esperar os resultados.",
    reversed: "Atrasos inesperados, obstáculos, falta de foresight. Planos que enfrentam dificuldades ou retornam sem sucesso.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 53, name: "Quatro de Paus", arcana: "minor", number: "4", suit: "wands",
    keywords: ["celebração","lar","comunidade","estabilidade"],
    upright: "Celebração, lar, comunidade, estabilidade, festividade. Momento de comemorar conquistas com aqueles que amamos, senso de pertencimento.",
    reversed: "Conflito doméstico, instabilidade no lar, falta de suporte. Tensões que perturbam a harmonia do lar.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 54, name: "Cinco de Paus", arcana: "minor", number: "5", suit: "wands",
    keywords: ["conflito","competição","discordância","caos"],
    upright: "Conflito, competição, discordância, caos produtivo. Diferentes pontos de vista em choque — pode ser desafiador mas também estimulante.",
    reversed: "Evitando conflito, resolução de disputas, encontrando harmonia. Conflitos se resolvendo ou necessidade de evitar confrontos desnecessários.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 55, name: "Seis de Paus", arcana: "minor", number: "6", suit: "wands",
    keywords: ["vitória","reconhecimento","progresso","autoconfiança"],
    upright: "Vitória, reconhecimento público, progresso, autoconfiança, triunfo. O herói retorna vitorioso — momento de celebrar conquistas e receber reconhecimento merecido.",
    reversed: "Ego inflado, queda de poder, falta de reconhecimento. Sucesso que traz arrogância ou vitória que passa despercebida.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 56, name: "Sete de Paus", arcana: "minor", number: "7", suit: "wands",
    keywords: ["defesa","perseverança","desafio","posição"],
    upright: "Defesa da posição, perseverança, desafio, manter o terreno conquistado. Em posição elevada mas sendo desafiado — é necessário defender o que foi conquistado.",
    reversed: "Capitulação, exaustão, rendição, ceder desnecessariamente. Dificuldade em manter a posição ou ceder por cansaço.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 57, name: "Oito de Paus", arcana: "minor", number: "8", suit: "wands",
    keywords: ["movimento rápido","progresso","notícias","alinhamento"],
    upright: "Movimento rápido, progresso acelerado, notícias chegando, alinhamento de forças. Tudo está em movimento — as coisas estão se acelerando em direção ao objetivo.",
    reversed: "Atrasos, frustração, falta de alinhamento, comunicação bloqueada. Forças que deveriam estar alinhadas estão em descompasso.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 58, name: "Nove de Paus", arcana: "minor", number: "9", suit: "wands",
    keywords: ["resiliência","perseverança","testado","guardar forças"],
    upright: "Resiliência, perseverança, defensor guardando forças. Quase lá — apesar dos ferimentos, é necessário continuar. A perseverança será recompensada.",
    reversed: "Exaustão extrema, paranoia, teimosia, desistência. Forças esgotadas ou recusa em descansar quando necessário.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 59, name: "Dez de Paus", arcana: "minor", number: "10", suit: "wands",
    keywords: ["sobrecarga","responsabilidade","fardo","completar"],
    upright: "Sobrecarga, responsabilidade excessiva, fardo, mas quase chegando. Carregando mais do que deveria — mas o destino está próximo.",
    reversed: "Deixar ir, delegação, encontrando soluções para o fardo. Necessidade de redistribuir responsabilidades ou simplificar.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 60, name: "Pajem de Paus", arcana: "minor", number: "11", suit: "wands",
    keywords: ["entusiasmo","exploração","descoberta","potencial"],
    upright: "Entusiasmo, exploração, potencial, mensagem inspiradora. Jovem espírito cheio de energia criativa pronto para novas aventuras.",
    reversed: "Novidade sem substância, falta de direção, energia desperdiçada. Entusiasmo sem foco ou follow-through.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 61, name: "Cavaleiro de Paus", arcana: "minor", number: "12", suit: "wands",
    keywords: ["energia","paixão","aventura","impulsividade"],
    upright: "Energia, paixão, aventura, charme, busca por emoções. Vive intensamente no presente, seguindo a paixão onde ela levar.",
    reversed: "Impulsividade, frustração, aventuras mal planejadas. Energia sem direção causando caos.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 62, name: "Rainha de Paus", arcana: "minor", number: "13", suit: "wands",
    keywords: ["confiança","coragem","paixão","liderança natural"],
    upright: "Confiança, coragem, paixão, liderança natural, magnetismo. Mulher de presença poderosa que inspira com sua energia vital e confiança.",
    reversed: "Insegurança, introversão repentina, ciúme, demandas excessivas. A confiança natural se transformando em comportamento controlador.",
    element: "Fogo", planet: null, symbol: "🔥" },
  { id: 63, name: "Rei de Paus", arcana: "minor", number: "14", suit: "wands",
    keywords: ["visão","liderança","empreendedorismo","inspiração"],
    upright: "Visão, liderança inspiradora, empreendedorismo, honra. Líder visionário que inspira através da paixão e do exemplo.",
    reversed: "Impetuosidade, dominação, arrogância, expectativas impossíveis. Liderança que se torna tiranicamente exigente.",
    element: "Fogo", planet: null, symbol: "🔥" },

  // OUROS (1-14)
  { id: 64, name: "Ás de Ouros", arcana: "minor", number: "1", suit: "pentacles",
    keywords: ["manifestação","prosperidade","oportunidade","abundância"],
    upright: "Manifestação, prosperidade, oportunidade material, novo começo financeiro. A semente dourada de toda abundância. Momento propício para iniciar projetos materiais.",
    reversed: "Oportunidade perdida, falta de planejamento, instabilidade financeira. A semente não encontra solo fértil.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 65, name: "Dois de Ouros", arcana: "minor", number: "2", suit: "pentacles",
    keywords: ["equilíbrio","adaptação","malabarismo","fluxo"],
    upright: "Equilíbrio, adaptação, malabarismo de responsabilidades, fluxo. Dançando com as mudanças da vida — manter o equilíbrio enquanto múltiplas demandas competem por atenção.",
    reversed: "Desequilíbrio, desorganização, sobrecarga, problemas financeiros. Muitas bolas no ar e algumas estão caindo.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 66, name: "Três de Ouros", arcana: "minor", number: "3", suit: "pentacles",
    keywords: ["trabalho em equipe","habilidade","colaboração","aprendizado"],
    upright: "Trabalho em equipe, habilidade artesanal, colaboração, aprendizado. O mestre trabalha com outros — combinação de talentos para criar algo maior.",
    reversed: "Falta de trabalho em equipe, mediocridade, falta de esforço. Trabalho isolado ou falta de compromisso com a qualidade.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 67, name: "Quatro de Ouros", arcana: "minor", number: "4", suit: "pentacles",
    keywords: ["segurança","controle","conservadorismo","possessividade"],
    upright: "Segurança financeira, conservadorismo, controle, possessividade. Segurando firmemente o que foi conquistado — mas cuidado para não deixar o apego bloquear o crescimento.",
    reversed: "Generosidade, deixar ir, instabilidade financeira. Liberação do apego excessivo ou perda de controle financeiro.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 68, name: "Cinco de Ouros", arcana: "minor", number: "5", suit: "pentacles",
    keywords: ["dificuldade financeira","isolamento","pobreza","exclusão"],
    upright: "Dificuldade financeira, isolamento, pobreza, exclusão. Período difícil materialmente — mas o abrigo e o suporte estão disponíveis para quem busca.",
    reversed: "Recuperação financeira, fim de dificuldades, ajuda chegando. Saindo do período de escassez em direção à estabilidade.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 69, name: "Seis de Ouros", arcana: "minor", number: "6", suit: "pentacles",
    keywords: ["generosidade","dar e receber","caridade","equilíbrio"],
    upright: "Generosidade, dar e receber, caridade, distribuição equitativa. O ciclo saudável de dar e receber — abundância que flui.",
    reversed: "Strings attached, doação com expectativas, dívida, ganância. Generosidade que esconde controle ou desequilíbrio na troca.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 70, name: "Sete de Ouros", arcana: "minor", number: "7", suit: "pentacles",
    keywords: ["paciência","investimento","crescimento","avaliação"],
    upright: "Paciência, investimento de longo prazo, crescimento, avaliação do progresso. O fazendeiro contempla sua colheita — alguns investimentos levam tempo para dar frutos.",
    reversed: "Impaciência, falta de crescimento, recompensas tardias, desperdício. Investimentos que não estão rendendo ou falta de visão de longo prazo.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 71, name: "Oito de Ouros", arcana: "minor", number: "8", suit: "pentacles",
    keywords: ["diligência","artesanato","aprendizado","dedicação"],
    upright: "Diligência, artesanato, aprendizado, dedicação ao trabalho. Aperfeiçoamento das habilidades através da prática constante — a excelência vem da dedicação.",
    reversed: "Falta de foco, mediocridade, perfeccionismo paralisante. Trabalho sem atenção à qualidade ou obsessão com perfeição.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 72, name: "Nove de Ouros", arcana: "minor", number: "9", suit: "pentacles",
    keywords: ["abundância","luxo","independência","autossuficiência"],
    upright: "Abundância, luxo, independência, autossuficiência, prazer nos frutos do trabalho. Desfrutando dos resultados de esforço e disciplina — bem merecido.",
    reversed: "Ganho fácil, sucesso superficial, dependência. Aparência de abundância sem a substância por baixo.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 73, name: "Dez de Ouros", arcana: "minor", number: "10", suit: "pentacles",
    keywords: ["riqueza","herança","família","legado"],
    upright: "Riqueza duradoura, herança, família, legado, estabilidade intergeracional. A realização completa no plano material — abundância que passa para as próximas gerações.",
    reversed: "Dívidas familiares, conflitos por herança, instabilidade financeira. Riqueza que traz divisão ou perda do que foi construído.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 74, name: "Pajem de Ouros", arcana: "minor", number: "11", suit: "pentacles",
    keywords: ["estudo","oportunidade","confiabilidade","aprendizado prático"],
    upright: "Estudo, oportunidade material, confiabilidade, aprendizado prático. Jovem dedicado ao aprendizado com os pés no chão.",
    reversed: "Falta de progresso, procrastinação, foco excessivo no material. Dificuldade em traduzir aprendizado em ação.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 75, name: "Cavaleiro de Ouros", arcana: "minor", number: "12", suit: "pentacles",
    keywords: ["trabalho duro","rotina","confiabilidade","persistência"],
    upright: "Trabalho duro, rotina, confiabilidade, persistência, resultado tangível. Avança devagar mas com certeza — a perseverança leva ao resultado.",
    reversed: "Tédio, rotina sufocante, perfeccionismo, estagnação. Excesso de cautela que impede o avanço.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 76, name: "Rainha de Ouros", arcana: "minor", number: "13", suit: "pentacles",
    keywords: ["nutrição","praticidade","abundância","segurança"],
    upright: "Nutrição, praticidade, abundância compartilhada, segurança, generosidade. A rainha que cuida com recursos práticos e amor concreto.",
    reversed: "Desequilíbrio trabalho-vida, insegurança financeira, sufocamento. Materialismo excessivo ou negligência do aspecto emocional.",
    element: "Terra", planet: null, symbol: "⭐" },
  { id: 77, name: "Rei de Ouros", arcana: "minor", number: "14", suit: "pentacles",
    keywords: ["abundância","prosperidade","segurança","liderança prática"],
    upright: "Abundância, prosperidade, segurança, liderança prática, sucesso material. Rei que governa com sabedoria prática e cria prosperidade duradoura.",
    reversed: "Materialismo, ganância, obstinação, fracasso nos negócios. Riqueza sem propósito ou uso abusivo do poder material.",
    element: "Terra", planet: null, symbol: "⭐" },
];
